[project]
name = "c2-go2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "aiortc>=1.9.0",
    "av>=12.3.0",
    "fastapi[all]>=0.124.4",
    "opencv-python>=4.13.0.92",
    "psutil>=7.2.2",
    "torch==2.1.0",
    "torchvision>=0.16.0",
    "ultralytics>=8.4.21",
    "unitree-sdk2py",
]

[tool.uv.sources]
unitree-sdk2py = { path = "../unitree_sdk2_python", editable = true }

